# Generated by rust2rpm 27
%bcond check 1

Name:           rebuilderd
Version:        0.22.0
Release:        %autorelease
Summary:        - independent build verification daemon

SourceLicense:  GPL-3.0-or-later
License:        GPL-3.0-or-later
# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/kpcyrd/rebuilderd
Source:         %{url}/archive/refs/tags/v%{version}.tar.gz
Patch:          rebuilderd-downgrade-bzip2.patch

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Rebuilderd - independent build verification daemon.}

%description %{_description}

%prep
%autosetup -n rebuilderd-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
mkdir -p %buildroot/%{_bindir}
cp target/rpm/rebuilderd-worker %buildroot/%{_bindir}
cp target/rpm/rebuilderd %buildroot/%{_bindir}
cp target/rpm/rebuildctl %buildroot/%{_bindir}

# systemd units
#install -m 644 %{_sourcedir}/%{name}-%{version}/contrib/systemd/rebuilderd.service %buildroot/%{_libdir}/systemd/system


%if %{with check}
%check
# compression tests fail somehow
%cargo_test -- --workspace --exclude rebuildctl
%endif

%files
#%license LICENSE
#%license LICENSE.dependencies
#%doc README.md
%{_bindir}/rebuildctl
%{_bindir}/rebuilderd
%{_bindir}/rebuilderd-worker

%changelog
%autochangelog
